# Generated by Django 4.1 on 2022-09-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="", max_length=20)),
                ("Email", models.CharField(default="", max_length=20)),
                ("Mobile", models.CharField(default="", max_length=20)),
                ("Message", models.CharField(default="", max_length=20)),
            ],
        ),
    ]
