# Generated by Django 4.1 on 2022-09-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="data", table="port",),
    ]
